export function useUi() {
  const locale = useState<string>('ui-locale', () => 'en')
  const themeMode = useState<string>('ui-theme', () => 'light')

  const messages: Record<string, Record<string, string>> = {
    en: {
      login: 'Login', logout: 'Logout', createUser: 'Create user', source: 'Source',
      cookiesMsg: 'This site uses cookies for login/session. Please accept to continue.', accept: 'Accept',
      searchBooks: 'Search books', search: 'Search', trending: 'Trending',
      topTrending: 'Top 10 trending books', firstResults: 'First 10 results for',
      title: 'Title', author: 'Author', summary: 'Summary', stars: 'Stars', comments: 'Comments', open: 'Open',
      rateComment: 'Rate & Comment', comment: 'Comment', saveReview: 'Save review', cancel: 'Cancel',
      selectStarFirst: 'Please select a star rating first.', loginToRate: 'You must login to comment or give stars.', loginNow: 'Login now',
      createAccount: 'Create account', forgotPassword: 'Forgot password', name: 'Name', password: 'Password',
      passwordMin: 'Password (min 8)', loginFailed: 'Login failed', registrationFailed: 'Registration failed',
      forgotTitle: 'Forgot password', generateReset: 'Generate reset', requestFailed: 'Request failed',
      dark: 'Dark', light: 'Light', language: 'Language', theme: 'Theme'
    },
    ro: { login:'Autentificare', logout:'Ieșire', createUser:'Creează utilizator', source:'Sursă', cookiesMsg:'Acest site folosește cookie-uri pentru sesiune. Te rugăm acceptă.', accept:'Accept', searchBooks:'Caută cărți', search:'Caută', trending:'Trend', topTrending:'Top 10 cărți populare', firstResults:'Primele 10 rezultate pentru', title:'Titlu', author:'Autor', summary:'Rezumat', stars:'Stele', comments:'Comentarii', open:'Deschide', rateComment:'Notă & comentariu', comment:'Comentariu', saveReview:'Salvează recenzia', cancel:'Anulează', selectStarFirst:'Selectează mai întâi stelele.', loginToRate:'Trebuie să te autentifici pentru a comenta sau nota.', loginNow:'Autentifică-te', createAccount:'Creează cont', forgotPassword:'Ai uitat parola', name:'Nume', password:'Parolă', passwordMin:'Parolă (minim 8)', loginFailed:'Autentificare eșuată', registrationFailed:'Înregistrare eșuată', forgotTitle:'Ai uitat parola', generateReset:'Generează resetare', requestFailed:'Cerere eșuată', dark:'Întunecat', light:'Luminos', language:'Limbă', theme:'Temă' },
    fr: { login:'Connexion', logout:'Déconnexion', createUser:'Créer utilisateur', source:'Source', cookiesMsg:'Ce site utilise des cookies pour la session. Veuillez accepter.', accept:'Accepter', searchBooks:'Rechercher des livres', search:'Rechercher', trending:'Tendance', topTrending:'Top 10 des livres tendance', firstResults:'10 premiers résultats pour', title:'Titre', author:'Auteur', summary:'Résumé', stars:'Étoiles', comments:'Commentaires', open:'Ouvrir', rateComment:'Note & commentaire', comment:'Commentaire', saveReview:'Enregistrer', cancel:'Annuler', selectStarFirst:'Sélectionnez d\'abord une note.', loginToRate:'Connectez-vous pour commenter ou noter.', loginNow:'Se connecter', createAccount:'Créer un compte', forgotPassword:'Mot de passe oublié', name:'Nom', password:'Mot de passe', passwordMin:'Mot de passe (min 8)', loginFailed:'Échec de connexion', registrationFailed:'Échec inscription', forgotTitle:'Mot de passe oublié', generateReset:'Générer reset', requestFailed:'Échec de requête', dark:'Sombre', light:'Clair', language:'Langue', theme:'Thème' },
    it: { login:'Accedi', logout:'Esci', createUser:'Crea utente', source:'Fonte', cookiesMsg:'Questo sito usa cookie per la sessione. Accetta.', accept:'Accetta', searchBooks:'Cerca libri', search:'Cerca', trending:'Tendenze', topTrending:'Top 10 libri di tendenza', firstResults:'Primi 10 risultati per', title:'Titolo', author:'Autore', summary:'Riassunto', stars:'Stelle', comments:'Commenti', open:'Apri', rateComment:'Voto e commento', comment:'Commento', saveReview:'Salva recensione', cancel:'Annulla', selectStarFirst:'Seleziona prima una valutazione.', loginToRate:'Devi accedere per commentare o votare.', loginNow:'Accedi ora', createAccount:'Crea account', forgotPassword:'Password dimenticata', name:'Nome', password:'Password', passwordMin:'Password (min 8)', loginFailed:'Accesso fallito', registrationFailed:'Registrazione fallita', forgotTitle:'Password dimenticata', generateReset:'Genera reset', requestFailed:'Richiesta fallita', dark:'Scuro', light:'Chiaro', language:'Lingua', theme:'Tema' },
    hu: { login:'Bejelentkezés', logout:'Kijelentkezés', createUser:'Felhasználó létrehozása', source:'Forrás', cookiesMsg:'Az oldal cookie-kat használ. Kérjük fogadd el.', accept:'Elfogadom', searchBooks:'Könyv keresése', search:'Keresés', trending:'Trend', topTrending:'Top 10 felkapott könyv', firstResults:'Első 10 találat erre', title:'Cím', author:'Szerző', summary:'Összefoglaló', stars:'Csillagok', comments:'Megjegyzések', open:'Megnyitás', rateComment:'Értékelés és komment', comment:'Komment', saveReview:'Értékelés mentése', cancel:'Mégse', selectStarFirst:'Előbb válassz csillagot.', loginToRate:'Értékeléshez be kell jelentkezned.', loginNow:'Jelentkezz be', createAccount:'Fiók létrehozása', forgotPassword:'Elfelejtett jelszó', name:'Név', password:'Jelszó', passwordMin:'Jelszó (min 8)', loginFailed:'Sikertelen belépés', registrationFailed:'Sikertelen regisztráció', forgotTitle:'Elfelejtett jelszó', generateReset:'Reset generálás', requestFailed:'Sikertelen kérés', dark:'Sötét', light:'Világos', language:'Nyelv', theme:'Téma' },
    de: { login:'Anmelden', logout:'Abmelden', createUser:'Benutzer erstellen', source:'Quelle', cookiesMsg:'Diese Seite verwendet Cookies für die Sitzung. Bitte akzeptieren.', accept:'Akzeptieren', searchBooks:'Bücher suchen', search:'Suchen', trending:'Trend', topTrending:'Top 10 Trend-Bücher', firstResults:'Erste 10 Ergebnisse für', title:'Titel', author:'Autor', summary:'Zusammenfassung', stars:'Sterne', comments:'Kommentare', open:'Öffnen', rateComment:'Bewertung & Kommentar', comment:'Kommentar', saveReview:'Bewertung speichern', cancel:'Abbrechen', selectStarFirst:'Bitte zuerst Sterne wählen.', loginToRate:'Zum Bewerten bitte anmelden.', loginNow:'Jetzt anmelden', createAccount:'Konto erstellen', forgotPassword:'Passwort vergessen', name:'Name', password:'Passwort', passwordMin:'Passwort (min. 8)', loginFailed:'Anmeldung fehlgeschlagen', registrationFailed:'Registrierung fehlgeschlagen', forgotTitle:'Passwort vergessen', generateReset:'Reset erzeugen', requestFailed:'Anfrage fehlgeschlagen', dark:'Dunkel', light:'Hell', language:'Sprache', theme:'Thema' }
  }

  const t = (k: string) => messages[locale.value]?.[k] || messages.en[k] || k
  return { locale, themeMode, t }
}
